//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityConstants {
    
    
    public sealed class Axes {
        
        public const string Horizontal = "Horizontal";
        
        public const string Vertical = "Vertical";
        
        public const string Fire1 = "Fire1";
        
        public const string Fire2 = "Fire2";
        
        public const string Fire3 = "Fire3";
        
        public const string Jump = "Jump";
        
        public const string MouseX = "Mouse X";
        
        public const string MouseY = "Mouse Y";
        
        public const string MouseScrollWheel = "Mouse ScrollWheel";
        
        public const string Submit = "Submit";
        
        public const string Cancel = "Cancel";
        
        private Axes() {
        }
    }
}
