//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityConstants {
    
    
    public sealed class Layers {
        
        public const string Default = "Default";
        
        public const string TransparentFX = "TransparentFX";
        
        public const string IgnoreRaycast = "Ignore Raycast";
        
        public const string Water = "Water";
        
        public const string UI = "UI";
        
        private Layers() {
        }
    }
}
