//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityConstants {
    
    
    public sealed class SortingLayers {
        
        public const string Default = "Default";
        
        private SortingLayers() {
        }
    }
}
